### ISSUE TITLE
How can I run Question Answering?

### ISSUE THREAD

**Issue by LeeDongYeun** [kaist-siit-lab/StarLab_1-2#2]
Hello,

Thank you for providing this great project! I am particularly interested in using the Question Answering feature with the LLM model included in the repository.

Could you provide guidance or instructions on:

1. How to set up and run the Question Answering functionality?
2. Any specific configurations, commands, or scripts required to enable this feature?
3. Example inputs and outputs to better understand how to interact with the model for this task?

Your detailed explanation will help me and others explore the potential of this functionality more effectively.

Thank you for your time and assistance!

Best regards

**Comment by koooooooook** [comment]
Thank you for your interest.
We summarized those this on run_QA.sh.
You can run QA functionality with it.
